sudo: required
dist: trusty
env:
  global:
  - GH_REF: github.com/FTSRG/remo-jegyzet.git
  - secure: D/sI1HUk702s8RwkfRUx5sXJ7h8Ph49EX3y+cYsIdcrUF4q3HtymCsVKu4LqjSlINOiLj74ZGDO23haie94eViB6ImVXnRe7i0momXCDlwYaCPlgYUmrRtu5F3TaQlCSm/j49C7H3dm/TtsHzYxy9WuhYU6Ld9P2GVmau/NJd0W7Hq8Ag3iPoST/IcXLMP3QtrV24DhNzZQBb9T9DURuY8Jxpw7wnWIq/D2CpVcosn4rXCIK4yRAil8gderuuXNjWZlNrxHvGFgvMtSiduQv8oyHoEsaIQIE/v9N6fUzxMzWpFg1nstYXshc4it7qOIixRydlom/LVRYQWzbHNJ7aDwY5ByusjMcHZ4m5t4LY5dNBFFzY/nuenmbvJRTm3EnlH5QlNFUsXysG7k0x78P+6yYt8itVN7mEje2WAs00s0/Md4GO+wdtqgTkUmx1qFjdK5LOLPTCUITDOPNyRaoqYt2gP1YjF1LqhoISmn7vaZon32ztSqwMKBXVk0jaJGlt7jRVihreWjg3BrMH3niutYzOoU6aIV51iibs7LECneGql8p7NpRXtwE5pz7HxmG2u0bkz36y1xlu1R7XdLrLKUHFe84EjtOFJLq8w6M1rae3R3Nbz4emvJHjMHo17LR1P7CYJhzhWR/lgGuteoIhm+RIVyOAkIafAPFQCqXxu4=
branches:
  only:
    - master
script:
- sudo apt-get update
- sudo apt-get install -y texlive-base texlive-science texlive-xetex texlive-fonts-recommended texlive-latex-extra texlive-lang-german texlive-lang-hungarian texlive-fonts-extra xindy
#- cd struktura-alapu-modellezes/figures/ && ./gs.sh && cd ../..
- ./use-xindy.sh
- make
- ./deploy.sh
notifications:
  slack: ftsrg:BtaOO3xw6rmfcFhEFNj6XJ29
